name       : dvgrab
version    : 3.5
release    : 2
source     :
    - http://netix.dl.sourceforge.net/project/kino/dvgrab/3.5/dvgrab-3.5.tar.gz : 5910183429d300221783d6054ff5add15bb2ae49ae33272d723a314bc2ce0af9
license    : GPL-2.0
component  : multimedia.video
summary    : Command line FireWire DV and HDV capture tool for Linux
description: |
    Command line FireWire DV and HDV capture tool for Linux
builddeps  :
    - pkgconfig(libavc1394)
    - pkgconfig(libdv)
    - pkgconfig(libiec61883)
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-iec13818-1.h-fix-build-with-GCC-6.1.0.patch
    %configure
build      : |
    %make
install    : |
    %make_install
